tdjniPath: D:\workspace\tdlib-use\lib
server:
  port: 8080
  servlet:
    context-path: /
spring:
  profiles:
    active: url
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dev_kok_sport?useUnicode=true&characterEncoding=utf8&autoReconnect=true&failOverReadOnly=false&useSSL=false
    username: root
    password: 123456
    platform: mysql
    type: com.alibaba.druid.pool.DruidDataSource
    # 下面为连接池的补充设置，应用到上面所有数据源中
    # 初始化大小，最小，最大
    initialSize: 1
    minIdle: 3
    maxActive: 20
    # 配置获取连接等待超时的时间
    maxWait: 60000
    # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
    timeBetweenEvictionRunsMillis: 60000
    # 配置一个连接在池中最小生存的时间，单位是毫秒
    minEvictableIdleTimeMillis: 30000
    # 验证连接有效与否的SQL，不同的数据配置不同
    validationQuery: select 1
    # 执行validationQuery检测连接是否有效。
    testWhileIdle: true
    # 申请连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能。
    # 这里建议配置为TRUE，防止取到的连接不可用
    testOnBorrow: true
    # 归还连接时执行validationQuery检测连接是否有效，做了这个配置会降低性能
    # testOnReturn: false
    # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
    filters: stat,wall
mybatis-plus:
  mapper-locations: mapper/*.xml
  type-aliases-package: com.sample.entity
logging:
  config: classpath:logback.xml
